apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: selfsigned
  namespace: appmesh-system
spec:
  selfSigned: {}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: inject-cert
  namespace: appmesh-system
spec:
  isCA: false
  dnsNames:
    - appmesh-inject
    - appmesh-inject.appmesh-system
    - appmesh-inject.appmesh-system.svc
  keyAlgorithm: rsa
  usages:
    - "digital signature"
    - "key encipherment"
  secretName: appmesh-inject
  issuerRef:
    name: selfsigned
