---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: appmesh-inject
  namespace: appmesh-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: appmesh-inject
rules:
  - apiGroups: ["*"]
    resources: ["replicasets"]
    verbs: ["get"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: appmesh-inject
subjects:
  - kind: ServiceAccount
    name: appmesh-inject
    namespace: appmesh-system
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: appmesh-inject
  apiGroup: ""
