---
apiVersion: v1
kind: Service
metadata:
  name: appmesh-inject
  namespace: appmesh-system
  labels:
    name: appmesh-inject
spec:
  ports:
  - name: webhook
    port: 443
    targetPort: 8080
  selector:
    name: appmesh-inject
